# Generated by Django 2.1.3 on 2019-01-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('email', models.CharField(blank=True, max_length=128, verbose_name='邮箱')),
                ('is_superuser', models.BooleanField(verbose_name='是否超级用户')),
                ('description', models.CharField(blank=True, max_length=128, verbose_name='描述')),
            ],
        ),
    ]
